
#
# A list of fake intro phrases, that make no sense without context.
#
# "???"
# "Again?"
# "But why?"
# "Can you?"
# "Explain it like I'm five."
# "Explain."
# "Horrible."
# "How?"
# "I don't believe you."
# "I don't care."
# "I don't know."
# "I don't think so."
# "I don't understand."
# "I know."
# "I love it."
# "I overheard."
# "I'd never."
# "Just forget it."
# "Let's do this."
# "Maybe."
# "My bad."
# "No way."
# "No."
# "Now what?"
# "Remind me."
# "The usual, I guess?"
# "Wait, what?"
# "What did you say?"
# "What do you mean?"
# "What's next?"
# "What's that?"
# "When?"
# "WTF?"
# "Yes."
# "You're lying."
# "You're wrong."
