model_name: pythia-14m
out_dir: out/pretrain
precision: bf16-mixed
resume: auto
data:
  class_path: litgpt.data.TextFiles
  init_args:
    train_data_path: data
    seed: 42
    num_workers: 4
train:
  save_interval: 200
  log_interval: 1
  global_batch_size: 64
  micro_batch_size: 8
  lr_warmup_steps: 100
  max_tokens: 1220000000
  tie_embeddings: false
  max_norm: 1.0
  min_lr: 6.0e-05
eval:
  interval: 200
  max_iters: 50
  initial_validation: false
  final_validation: false
  evaluate_example: first
log:
  log_model: false
  save_logs: true
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0006
    weight_decay: 0.1
    betas:
    - 0.9
    - 0.95
devices: auto
num_nodes: 1
tokenizer_dir: tokenizers/t-v2
logger_name: tensorboard
seed: 42
