attention_logit_softcapping: null
attention_scores_scalar: null
attn_bias: false
bias: true
block_size: 512
final_logit_softcapping: null
first_k_dense_replace: null
gelu_approximate: none
head_size: 32
hf_config:
  name: pythia-14m
  org: EleutherAI
intermediate_size: 512
latent_attention: null
lm_head_bias: false
mlp_class_name: GptNeoxMLP
moe_intermediate_size: null
n_embd: 128
n_expert: 0
n_expert_groups: null
n_expert_per_token: 0
n_head: 4
n_layer: 6
n_query_groups: 4
n_shared_expert: null
n_topk_groups: null
n_topk_scores_per_group: null
name: pythia-14m
norm_1: true
norm_2: true
norm_class_name: LayerNorm
norm_eps: 1.0e-05
norm_qk: false
norm_qk_type: default
norm_topk_prob: false
padded_vocab_size: 50304
padding_multiple: 128
parallel_residual: true
post_attention_norm: false
post_mlp_norm: false
rope_adjustments: null
rope_base: 10000
rope_condense_ratio: 1
rope_indices: null
rope_interleave: false
rope_local_base_freq: null
rotary_percentage: 0.25
routed_scaling_factor: 1.0
scale_embeddings: false
shared_attention_norm: false
sliding_window_indices: null
sliding_window_size: null
vocab_size: 50254
